/* GENERATED from shell/i18n/*.po by shell/tools/po2js.py — do not edit by hand.
 *
 * Add or change a string in the `.po` files, then re-run the generator and
 * commit both. The runtime helpers (t / setLang / pickLang) are NOT here —
 * they live in renderer/i18n.js, which this file never overwrites.
 */
const STRINGS = {
  en: {
    "cn.h": "Blave has no AI of its own.",
    "cn.blave.title": "Use Blave's AI",
    "cn.blave.desc": "Pay per use",
    "cn.blave.btn": "Sign in to Blave",
    "cn.blave.switch": "Switch",
    "cn.local.label": "Local agent",
    "cn.local.desc": "Your Claude Code or Codex — no Blave AI fee",
    "cn.redetect": "Detect again",
    "cn.detecting": "Detecting…",
    "cn.connect": "Connect",
    "cn.foot": "You can switch at any time.",
    "cn.back": "Back",
    "st.signedIn": "Signed in",
    "st.notSignedIn": "Not signed in",
    "st.notFound": "Not found",
    "hint.claudeLogin": "Run claude once in a terminal, sign in, then come back and press “Detect again”.",
    "oauth.waiting": "Waiting for the browser…",
    "oauth.cancel": "Cancel",
    "oauth.opened": "The authorization page is open in your browser. You'll come back here automatically.",
    "oauth.failed": "Authorization failed.",
    "OAUTH_CANCELLED": "Cancelled. Press the button again to use Blave's AI.",
    "OAUTH_TIMEOUT": "Authorization timed out (5 minutes).",
    "OAUTH_STATE_MISMATCH": "The reply didn't match this request and was rejected.",
    "OAUTH_NO_CODE": "The browser came back without an authorization code.",
    "OAUTH_DENIED": "You cancelled the authorization in the browser.",
    "KEYCHAIN_UNAVAILABLE": "This computer can't store credentials securely (Keychain unavailable), so nothing was saved.",
    "TOKEN_EXCHANGE_FAILED": "Could not exchange the authorization code for a token.",
    "ws.chatEmpty": "Describe a trading idea and I'll write it, backtest it, and show you the numbers.",
    "ws.chatExample": "Backtest a BTC 20/50 moving-average strategy",
    "ws.strategies": "Strategies",
    "ws.noStrategies": "No strategies yet.",
    "ws.nothingToSee": "Nothing to see yet.",
    "ws.placeholder": "Message the agent",
    "ws.send": "Send",
    "ws.connBlave": "Blave AI",
    "ws.connClaude": "Claude Code (your subscription)",
    "ws.connCodex": "Codex (your subscription)",
    "ws.conn": "Connected: {name}",
    "ws.settings": "Settings",
    "turn.process": "Thought process",
    "turn.thinking": "Thinking",
    "turn.running": "Running · step {n}",
    "turn.busy": "The previous turn is still running.",
    "turn.engineFailed": "Engine setup failed: {msg}",
    "turn.exit": "Engine exited with code {code}",
    "turn.error": "Something went wrong: {msg}",
    "fault.authInvalid": "This computer's Blave authorization is no longer valid (revoked or expired). This turn did not run.",
    "fault.authBtn": "Sign in again",
    "fault.noCredit": "Your Blave credit is empty. This turn did not run.",
    "fault.noCreditBtn": "Top up",
    "conn.expired": "Your Blave sign-in is no longer valid. Please sign in again.",
    "engine.workspace": "Creating the workspace at ~/Blave/workspace …",
    "engine.deps": "Installing the Python packages strategies need (pandas, numpy…), first run only…",
    "engine.preparing": "Preparing the engine (first run installs it, about a minute)…",
  },
  zh: {
    "cn.h": "Blave 不內建 AI。",
    "cn.blave.title": "用 Blave 的 AI",
    "cn.blave.desc": "按用量計費",
    "cn.blave.btn": "登入 Blave",
    "cn.blave.switch": "切換",
    "cn.local.label": "本機 agent",
    "cn.local.desc": "你的 Claude Code 或 Codex，Blave 不收 AI 費用",
    "cn.redetect": "重新偵測",
    "cn.detecting": "偵測中…",
    "cn.connect": "連結",
    "cn.foot": "連結後可以隨時更換。",
    "cn.back": "返回",
    "st.signedIn": "已登入",
    "st.notSignedIn": "尚未登入",
    "st.notFound": "未偵測到",
    "hint.claudeLogin": "在終端機跑一次 claude，完成登入後回到這裡按「重新偵測」。",
    "oauth.waiting": "等待瀏覽器授權…",
    "oauth.cancel": "取消等待",
    "oauth.opened": "已在瀏覽器開啟授權頁，完成後會自動回到這裡。",
    "oauth.failed": "授權失敗。",
    "OAUTH_CANCELLED": "已取消。要用 Blave 的 AI 再按一次。",
    "OAUTH_TIMEOUT": "授權逾時（5 分鐘）。",
    "OAUTH_STATE_MISMATCH": "回來的授權跟這次請求對不上，已擋下。",
    "OAUTH_NO_CODE": "瀏覽器回來了，但沒有帶授權碼。",
    "OAUTH_DENIED": "你在瀏覽器取消了授權。",
    "KEYCHAIN_UNAVAILABLE": "這台電腦無法安全儲存憑證（Keychain 不可用），沒有保存。",
    "TOKEN_EXCHANGE_FAILED": "授權碼換不到 token。",
    "ws.chatEmpty": "講一個交易想法，我把它寫成策略、跑完回測，把數字給你看。",
    "ws.chatExample": "回測一支 BTC 20/50 均線策略",
    "ws.strategies": "策略",
    "ws.noStrategies": "還沒有策略。",
    "ws.nothingToSee": "還沒有東西可以看。",
    "ws.placeholder": "跟 agent 說一句話",
    "ws.send": "送出",
    "ws.connBlave": "Blave AI",
    "ws.connClaude": "Claude Code（你的訂閱）",
    "ws.connCodex": "Codex（你的訂閱）",
    "ws.conn": "已連結：{name}",
    "ws.settings": "設定",
    "turn.process": "思考過程",
    "turn.thinking": "思考中",
    "turn.running": "執行中 · 第 {n} 步",
    "turn.busy": "上一輪還在跑。",
    "turn.engineFailed": "引擎準備失敗：{msg}",
    "turn.exit": "引擎退出碼 {code}",
    "turn.error": "出錯了：{msg}",
    "fault.authInvalid": "這台電腦的 Blave 授權已失效（被撤銷或過期），這一輪沒有跑。",
    "fault.authBtn": "重新登入",
    "fault.noCredit": "Blave 額度不足，這一輪沒有跑。",
    "fault.noCreditBtn": "儲值",
    "conn.expired": "Blave 登入已失效，請重新登入。",
    "engine.workspace": "建立工作區 ~/Blave/workspace …",
    "engine.deps": "正在安裝策略需要的 Python 套件（pandas、numpy…），只有第一次…",
    "engine.preparing": "正在準備引擎（第一次會安裝，約一分鐘）…",
  },
};
