/* GENERATED from shell/i18n/*.po by shell/tools/po2js.py — do not edit by hand.
 *
 * Add or change a string in the `.po` files, then re-run the generator and
 * commit both. The runtime helpers (t / setLang / pickLang) are NOT here —
 * they live in renderer/i18n.js, which this file never overwrites.
 */
const STRINGS = {
  en: {
    "cn.h": "Blave has no AI of its own.",
    "cn.blave.title": "Use Blave's AI",
    "cn.blave.desc": "First card adds 100 TWD of AI credit, then pay per use",
    "cn.blave.btn": "Sign in to Blave",
    "cn.blave.switch": "Switch",
    "cn.local.label": "Agents on this computer",
    "cn.local.desc": "No AI charges from Blave",
    "cn.redetect": "Detect again",
    "cn.detecting": "Detecting…",
    "cn.connect": "Connect",
    "cn.foot": "You can switch at any time.",
    "st.signedIn": "Signed in",
    "st.notSignedIn": "Not signed in",
    "st.notFound": "Not found",
    "oauth.waiting": "Waiting for the browser…",
    "oauth.cancel": "Cancel",
    "oauth.opened": "The authorization page is open in your browser. You'll come back here automatically.",
    "oauth.failed": "Authorization failed.",
    "OAUTH_CANCELLED": "Cancelled. Press the button again to use Blave's AI.",
    "OAUTH_TIMEOUT": "Authorization timed out (5 minutes).",
    "OAUTH_STATE_MISMATCH": "The reply didn't match this request and was rejected.",
    "OAUTH_NO_CODE": "The browser came back without an authorization code.",
    "OAUTH_DENIED": "You cancelled the authorization in the browser.",
    "KEYCHAIN_UNAVAILABLE": "This computer can't store credentials securely (Keychain unavailable), so nothing was saved.",
    "TOKEN_EXCHANGE_FAILED": "Could not exchange the authorization code for a token.",
    "ws.chatExample": "Backtest a BTC 20/50 moving-average strategy",
    "ws.strategies": "Strategies",
    "ws.noStrategies": "No strategies yet.",
    "ws.placeholder": "Message the agent",
    "ws.send": "Send",
    "ws.settings": "Settings",
    "turn.process": "Thought process",
    "turn.thinking": "Thinking",
    "turn.running": "Running · step {n}",
    "turn.busy": "The previous turn is still running.",
    "turn.engineFailed": "Engine setup failed: {msg}",
    "turn.exit": "Engine exited with code {code}",
    "turn.error": "Something went wrong: {msg}",
    "fault.authInvalid": "This computer’s Blave sign-in is no longer valid, so this turn didn’t run.",
    "fault.authBtn": "Sign In Again",
    "fault.noCredit": "Your Blave balance is empty, so this turn didn’t run.",
    "fault.noCreditBtn": "Top Up",
    "conn.expired": "Your Blave sign-in is no longer valid. Sign in again to continue.",
    "engine.workspace": "Creating the workspace at ~/Blave/workspace …",
    "engine.deps": "Installing the Python packages strategies need (pandas, numpy…), first run only…",
    "engine.preparing": "Preparing the engine (first run installs it, about a minute)…",
    "mp.model": "Model",
    "mp.effort": "Effort",
    "mp.default": "Default",
    "mp.aria": "Model and effort: {model}, {effort}",
    "mp.ariaNoEffort": "Model: {model}",
    "mp.cap": "Default for {model}: {level}. Higher thinks longer and uses more.",
    "mp.none": "This model has no effort setting.",
    "lv.low": "Low",
    "lv.medium": "Medium",
    "lv.high": "High",
    "lv.xhigh": "Extra High",
    "lv.max": "Max",
    "lv.ultra": "Ultra",
    "fault.noModel": "Your account can't use {model}. This turn did not run.",
    "fault.noModelSwitched": "Your account can't use {model}. This turn did not run — switched back to {to}.",
    "fault.noModelBtn": "Choose a Model",
    "mp.na": "Not on your plan",
    "rp.tab.backtest": "Backtest",
    "rp.tab.trades": "Trades",
    "rp.tab.code": "Code",
    "bt.fee": "fee",
    "bt.totalReturn": "Total Return",
    "bt.benchmark": "Benchmark",
    "bt.benchmarkRank": "Beat {n}% of random portfolios",
    "bt.sharpe": "Sharpe",
    "bt.maxDrawdown": "Max Drawdown",
    "bt.trades": "Trades",
    "bt.mcpt": "MCPT p-value",
    "bt.mcptTipSig": "Shuffled {n} times; only {pct} of the shuffles beat it. Below 0.05 is the usual bar.",
    "bt.mcptTipNs": "Shuffled {n} times; {pct} of the shuffles beat it — above the usual 0.05 bar, so this result can't be told apart from luck.",
    "bt.equity": "Equity",
    "bt.drawdown": "Drawdown",
    "bt.chartAria": "Equity curve and drawdown over the backtest period",
    "bt.monthly": "Monthly returns",
    "bt.year": "Year",
    "bt.empty": "No backtest data for this strategy.",
    "tr.empty": "This strategy has no entries or exits.",
    "tr.chartError": "Couldn't draw the chart. The entries and exits below are still available.",
    "tr.list": "Entries & exits",
    "tr.count": "{n} trades",
    "tr.buy": "Buy",
    "tr.sell": "Sell",
    "tr.kind.open": "Open",
    "tr.kind.close": "Close",
    "tr.kind.flip": "Flip",
    "tr.position": "Position {n}",
    "bt.grpReturns": "Returns",
    "bt.grpRisk": "Risk",
    "bt.grpTrading": "Trading",
    "bt.annReturn": "Annualized Return",
    "bt.annVol": "Annualized Vol",
    "bt.sortino": "Sortino",
    "bt.omega": "Omega",
    "bt.winRate": "Daily Win Rate",
    "bt.totalFees": "Total Fees",
    "bt.mcptDistTitle": "MCPT · Sharpe across {n} shuffles, p = {p}",
    "bt.mcptDistActual": "Actual Sharpe {v}",
    "bt.mcptDistUnit": "shuffles",
    "ws.resizeSide": "Resize strategy list",
    "ws.resizeChat": "Resize chat",
    "ws.sideCollapse": "Collapse strategy list",
    "ws.sideExpand": "Expand strategy list",
    "ws.chatCollapse": "Collapse chat",
    "ws.chatExpand": "Expand chat",
    "set.close": "Close",
    "set.cats": "Settings categories",
    "set.cat.display": "General",
    "set.cat.model": "Model access",
    "set.lang": "Language",
    "up.app": "Blave {v}",
    "up.latest": "Up to date",
    "up.checking": "Checking for updates…",
    "up.downloading": "Downloading {nv}…",
    "up.downloadingPct": "Downloading {nv} ({pct}%)",
    "up.ready": "{nv} is downloaded and takes effect after a restart",
    "up.blocked": "{nv} is downloaded. Blave won’t update while auto trading is running — pause trading to update, or it installs when you quit Blave",
    "up.error": "The update check didn’t go through",
    "up.staging": "{nv} downloaded, preparing to install…",
    "up.installFailed": "{nv} was downloaded but couldn’t be installed. Make sure Blave is in your Applications folder (not opened straight from the disk image), then check again",
    "up.install": "Restart and update",
    "up.check": "Check for updates",
    "cn.current": "In use",
    "cs.all": "All chats",
    "cs.back": "Back to chat",
    "cs.new": "New chat",
    "cs.del": "Delete chat",
    "cs.delConfirm": "Delete?",
    "strat.del": "Move to Trash",
    "bt.tip.totalReturn": "Cumulative return over the whole backtest, net of fees.",
    "bt.tip.annReturn": "Total return converted to a compounded yearly rate, so backtests of different lengths can be compared.",
    "bt.tip.benchmark": "What buying and holding this symbol over the same period would have returned. The strategy has to beat it to be better than doing nothing.",
    "bt.tip.benchmarkRank": "Share of randomly picked buy-and-hold portfolios that this strategy’s total return beats.",
    "bt.tip.annVol": "Standard deviation of daily returns, scaled to a year. Higher means a bumpier equity curve.",
    "bt.tip.maxDrawdown": "Largest fall from a peak to the lowest point after it — how much you would have been down at the worst moment.",
    "bt.tip.sharpe": "Return earned per unit of volatility (annualized, risk-free rate taken as 0). Higher is better.",
    "bt.tip.sortino": "Same as Sharpe, but only downside volatility counts as risk; upside swings are not penalized.",
    "bt.tip.omega": "Sum of all gains divided by sum of all losses. Above 1 means it made more than it lost.",
    "bt.tip.trades": "Number of position changes: each entry, exit, or resize counts once.",
    "bt.tip.winRate": "Share of days with a gain, among days that had any P&L. This is not a per-trade win rate.",
    "bt.tip.totalFees": "All fees paid over the period, as a percentage of capital.",
    "del.title": "Delete “{title}”?",
    "del.titleCur": "Delete this conversation?",
    "del.body": "This conversation’s chat history will be deleted and can’t be restored. Your strategies are not affected.",
    "del.bodyCur": "Its chat history will be deleted and can’t be restored. A new chat will open. Your strategies are not affected.",
    "del.cancel": "Cancel",
    "del.ok": "Delete",
    "chat.imageAlt": "Chart from the agent",
    "cn.signIn": "Sign in",
    "login.opened": "{name} sign-in is open in your browser. Come back here when you’re done.",
    "login.ok": "{name} is signed in.",
    "login.failed": "{name} sign-in didn’t finish.",
    "fault.localAuth": "{name} isn’t signed in, so this turn didn’t run.",
    "fault.localAuthBtn": "Sign In to {name}",
    "chat.imageZoom": "View larger",
    "login.cancel": "Cancel",
    "login.failedCmd": "Or run {cmd} in a terminal.",
    "login.retry": "Try Again",
    "fault.resend": "Send Again",
    "fault.resendDone": "Sent Again",
    "fault.authOk": "Blave is signed in again.",
    "cn.blave.signOut": "Sign out",
    "cn.blave.signOutLocalOnly": "Signed out on this computer, but the server couldn’t be reached to revoke this device. Revoke it under Settings › Devices on blave.org.",
    "acct.noCard": "Blave’s AI isn’t ready yet: this account has no card on file.",
    "acct.noCredit": "Blave’s AI isn’t ready yet: the balance is 0.",
    "acct.addCard": "Add a Card",
    "acct.sub": "A first card comes with {q} TWD of AI credit, plus Blave data in the desktop app for {t} days.",
    "acct.ready": "Ready to go.",
    "acct.creditIn": "Credit is in. You can send again.",
    "fault.needCard": "Blave’s AI needs a card on file, so this turn didn’t run.",
    "fault.checking": "This turn didn’t run — checking your account.",
    "set.cat.plan": "Data & cloud plan",
    "plan.st.running": "Active · machine running",
    "plan.st.stopped": "Stopped · balance under {m} TWD",
    "plan.st.stoppedNoAmt": "Stopped · balance too low",
    "plan.bill": "Billing",
    "plan.month": "{p} TWD / month",
    "plan.hour": "30 days = {h} TWD from your balance every hour",
    "plan.trialFree": "No machine fee until {d}. After that, the price above applies.",
    "plan.topup": "Under a balance of {a} TWD, your card is charged {b} TWD automatically. You can turn this off on the web.",
    "plan.start": "Start Plan",
    "plan.starting": "Starting…",
    "plan.addCredit": "Add Credit",
    "plan.addCard": "Add a Card",
    "plan.openWs": "Open Workspace",
    "plan.manage": "Turn off on the web",
    "plan.manageStopped": "Manage on the web",
    "cf.title": "Start the Blave Agent Cloud Plan?",
    "cf.body1": "This opens a cloud machine for this account, usually in about a minute. Blave data is available as soon as you start.",
    "cf.body2": "Once it’s up, {h} TWD comes out of your balance every hour ({p} TWD a month, 30 days), for as long as the machine exists, in use or not.",
    "cf.body2Trial": "No machine fee until {d}. After that, {h} TWD comes out of your balance every hour, for as long as the machine exists, in use or not.",
    "cf.body3": "To stop the charges, delete the machine on the web.",
    "cf.ok": "Start",
    "plan.err.credit": "Not started: the balance is too low.",
    "plan.err.nocard": "Not started: this account has no card on file.",
    "plan.err.relogin": "Sign in again before starting the plan. Your chats and strategies aren’t affected.",
    "plan.relogin": "Sign In Again",
    "plan.err.server": "The plan didn’t start. Pressing again won’t create a second machine.",
    "plan.err.rate": "Too many attempts. Try again in a while. A second machine won’t be created.",
    "plan.err.slow": "Taking longer than usual. The machine is still starting, so there’s no need to press again.",
    "plan.recheck": "Check Again",
    "data.starting": "Your cloud machine is starting. Blave data will be available in a moment.",
    "plan.done": "Your cloud machine is up.",
    "side.trial": "{n} days left",
    "side.starting": "Starting",
    "side.stopped": "Stopped",
    "data.ready": "Blave data is now available.",
    "pv.h.offer": "Your first card comes with {t} days of Blave data",
    "pv.h.offerNoNum": "Your first card comes with a trial period of Blave data",
    "pv.h.plan": "A cloud machine where strategies go live, Blave data included",
    "pv.h.ready": "Blave data is now available",
    "pv.h.starting": "Your cloud machine is starting. It usually takes about a minute",
    "pv.h.running": "Your strategies can now go live on the cloud machine",
    "pv.h.stopped": "The machine is stopped but still billing",
    "pv.h.unknown": "Couldn’t check this account",
    "pv.d.offer.cli": "AI stays on your {name}. When a strategy has to run around the clock, the cloud machine has no machine fee for those {t} days.",
    "pv.d.offer.blave": "Plus {q} TWD of AI credit. When a strategy has to run around the clock, the cloud machine has no machine fee for those {t} days.",
    "pv.d.noTrial": "The Blave Agent Cloud Plan, {p} TWD a month. This account has no first-card trial: add a card, then start the plan here to get data.",
    "pv.d.trial": "Until {d}, there’s no need to start the plan. After that, data comes with the Blave Agent Cloud Plan: {p} TWD a month.",
    "pv.d.plan": "The Blave Agent Cloud Plan, {p} TWD a month. Strategies run on schedule and place orders on this machine. The desktop app works without it, just without Blave data.",
    "pv.d.included": "You only need the Blave Agent Cloud Plan when a strategy has to run around the clock: {p} TWD a month.",
    "pv.d.starting": "Blave data is available right now, before the machine is up. You can close this window.",
    "pv.d.running": "Add strategies, set up scheduled reports and connect an exchange on this machine from the workspace. Strategies built on this computer stay on this computer.",
    "pv.d.stopped": "A stopped machine still bills {h} TWD an hour. At a balance of 0 the machine is deleted, along with the strategies and data on it.",
    "pv.d.noPrice": "Your AI setup stays as it is. After the trial, data comes with the Blave Agent Cloud Plan, if you start it.",
    "pv.d.unknown": "This may be a network problem. Checking again costs nothing.",
    "pv.f.out": "After {t} days, data comes with the cloud plan ({p} TWD a month), if you start it.",
    "pv.f.offer": "A {v} TWD card check goes to your balance, and auto top-up turns on. After {t} days, data comes with the cloud plan ({p} TWD a month), if you start it.",
    "pv.f.noTrial": "Adding the card tops up at least {b} TWD, all of it added to your balance, and turns on auto top-up.",
    "pv.f.trial": "When a strategy has to run around the clock, you can start now: no machine fee until {d}, then billed while the machine exists. Only deleting it ends the charges.",
    "pv.f.plan": "{h} TWD from your balance every hour, for as long as the machine exists. A stopped machine still bills. Only deleting it ends the charges.",
    "pv.f.running": "{h} TWD an hour from your balance ({p} TWD a month). Turning it off means deleting the machine on the web, with the strategies and data on it.",
    "pv.w.out.cli": "Signing in costs nothing and keeps your AI. Next: add a card.",
    "pv.w.noTrial": "Next: come back and start the plan.",
    "pv.w.waiting": "Your browser is open. Press Allow there.",
    "pv.st.trial": "Trial · {n} days left",
    "pv.st.none": "Not started",
    "pv.st.ok": "Available",
    "pv.st.starting": "Starting",
    "pv.more": "What’s included and billing",
    "plan.inc": "Included",
    "plan.rule": "Billed for as long as the machine exists, in use or not. A stopped machine still bills. Only deleting it ends the charges.",
    "plan.rule.running": "Billed for as long as the machine exists, in use or not. Turning the plan off means deleting the machine, along with the strategies and data on it.",
    "pv.more.once": "The first-card trial is once per person and once per card.",
    "pv.inc.1": "A cloud machine that stays on 24 hours: strategies run on schedule and place orders",
    "pv.inc.2": "Blave data, in the desktop app and on the cloud machine",
    "pv.inc.3": "Operate the machine from the browser workspace",
    "pv.inc.note": "Strategies built on this computer stay on this computer. Strategies on the machine are built in the workspace, where exchange keys are connected too.",
    "pv.signin": "Sign in to Blave",
    "pv.e.out": "This computer can’t reach Blave data yet. Sign in to Blave, and your first card comes with {t} days of it. AI stays on your {name}.",
    "pv.e.outNoNum": "This computer can’t reach Blave data yet. Sign in to Blave, and your first card comes with a trial period of it. AI stays on your {name}.",
    "pv.e.card": "This computer can’t reach Blave data yet. Your first card comes with {t} days of it.",
    "pv.e.card.cli": "This computer can’t reach Blave data yet. Your first card comes with {t} days of it. AI stays on your {name}.",
    "pv.e.noTrial": "This computer can’t reach Blave data yet. It comes with the Blave Agent Cloud Plan.",
    "pv.e.sub": "After that, data comes with the Blave Agent Cloud Plan at {p} TWD a month.",
    "pv.e.subN": "{p} TWD a month: a cloud machine where strategies run around the clock, Blave data included. Billed hourly for as long as the machine exists.",
    "pv.e.unknown": "This computer can’t reach Blave data yet. The account status couldn’t be checked. Open Data & Cloud Plan to check again.",
    "pv.e.btn": "Data & Cloud Plan",
    "cn.blave.signinSwitch": "Sign In and Switch",
    "set.cat.acct": "Account",
    "cn.blave.name": "Blave’s AI",
    "cn.blave.group": "Provided by Blave",
    "acct.out.1": "After signing out, this computer no longer gets Blave data.",
    "acct.out.2": "Chats and strategies stay on this computer and aren’t affected.",
    "acct.out.3": "You’re using Blave’s AI, so signing out returns you to the AI picker. You’ll need to pick one again before you can carry on.",
    "acct.in.1": "Signing in is what gives you Blave data and the cloud plan.",
    "acct.in.2": "Signing in costs nothing and doesn’t change the AI you use.",
    "acct.toPlan": "Balance, card and the cloud plan are under Data & cloud plan.",
    "acct.toPlanBtn": "Open",
    "acct.lbl": "Blave account",
    "acct.signedOut": "Signed out",
    "acct.signedIn": "Signed in",
    "acct.out": "Sign out",
    "acct.outDone": "Signed out. This computer no longer gets Blave data.",
    "cx.lead": "Only in this computer’s workspace (~/Blave/workspace/.env). Blave does not upload them. The agent and your strategy code can read them; that is how they trade and fetch data for you.",
    "cx.note.one": "When you create the key on Binance: enable trading only, keep withdrawals off, and whitelist this IP.",
    "cx.store.q": "Where are my keys stored?",
    "cx.acct.meta": "Can place orders and read the account, and is also used to fetch this exchange's data. One at a time.",
    "cx.venue": "Exchange / broker",
    "cx.paper": "Paper trading (no keys)",
    "cx.paperShort": "Paper trading",
    "cx.paperNote": "No API keys needed. The simulated account starts with 10,000 USDT, fills at your strategy's own market data with fees (no slippage), and never touches real money; strategies, order settings, positions and the performance page all work exactly as with a real account. To switch to a real exchange later, unbind first, then connect.",
    "cx.connect": "Connect an exchange",
    "cx.connecting": "Connecting…",
    "cx.connected": "Connected",
    "cx.perfNote": "Paper results do not represent real fills (no slippage).",
    "cx.retest": "Retest connection",
    "cx.retesting": "Testing…",
    "cx.fail": "Connecting {id} failed ({stage}): {msg}",
    "cx.failShort": "Connection failed",
    "cx.sendFail": "Could not connect ({err}). Try again.",
    "cx.down": "The order engine on this computer isn't running. Try again in a few seconds; if it stays this way, restart Blave.",
    "tr.mode.paper": "Paper",
    "tr.tb": "{state} · {venue}",
    "tr.tbAria": "Auto trading: {state}",
    "tr.paperCcy": "paper {c}",
    "tr.nav": "Auto trading",
    "tr.autoOn": "Auto-trading running",
    "tr.halted": "Paused",
    "tr.recDead": "Reconciler not running",
    "tr.lastBeat": "last heartbeat {t}",
    "tr.notStarted": "Trading not started yet",
    "tr.noAccount": "No exchange connected",
    "tr.loading": "Loading…",
    "tr.stop": "Pause trading",
    "tr.start": "Start trading",
    "tr.stopping": "Pausing…",
    "tr.starting": "Starting…",
    "tr.cmdNotDelivered": "The command was never delivered — it is still trading. Try again; if it keeps failing, revoke this computer's API key at the exchange and it can no longer send orders (existing positions still need closing there yourself).",
    "tr.cmdUnavailable": "This computer’s command channel is not responding — commands can’t be sent from here right now.",
    "tr.cmdFailed": "The command was not delivered — nothing changed. Try again.",
    "tr.cmdUnknown": "The command was sent, but this computer has not reported a result yet — it may already have run. Check the status on this page before pressing again.",
    "tr.cmdRejected": "This computer rejected the command ({err}).",
    "tr.hostRetry": "The order engine on this computer stopped and is restarting; no orders go out meanwhile. Once it is back, check the status here — if it shows not started, press Start trading again.",
    "tr.hostShort": "Order engine not running",
    "tr.hostDown": "The order engine on this computer won't start, so auto-trading is not running. Restart Blave.",
    "tr.unknown": "Can't read the trading status on this computer",
    "tr.unknownBody": "The trading status couldn’t be read this round, so the account and positions can’t be shown for now. It will try again in a few seconds.",
    "tr.unknownStop": " The order engine may still be running; to stop it, press Pause trading above.",
    "tr.badAmount": "That amount can't be read. Numbers only, e.g. 1500 or 1,500.50; the limit is 1,000,000,000.",
    "tr.stopChoiceSelf": "No new positions will be opened after pausing. Closing positions only closes positions opened by auto-trading — anything you opened manually is left untouched.",
    "tr.stopChoice": "No new positions will be opened after pausing. Closing positions here market-closes ALL positions on this account, including ones you opened manually.",
    "tr.closeAllWarn2": "Strategy amounts are kept: pressing Start trading later rebuilds positions to those amounts. If you don't want that, zero the amounts first.",
    "tr.stopKeep": "Pause, leave positions untouched",
    "tr.stopFlat": "Pause and close positions",
    "tr.startChoice": "Catch up places market orders now to match each strategy’s current signal — if a strategy is already in a position, you board it mid-trade. Wait for new signals places no orders now; each strategy starts trading only at its next entry, exit, or flip.",
    "tr.startWarn1": "Real orders resume immediately, moving your exchange positions to the current targets.",
    "tr.startWarn2": "Strategies and weights kept updating while paused, so the first reconcile may move several positions at once.",
    "tr.startCatchUp": "Start and catch up positions",
    "tr.startWait": "Start, wait for new signals",
    "tr.means.l": "Running on this computer means:",
    "tr.means.1": "Auto-trading runs only while the computer is awake, Blave is open and the network is up.",
    "tr.means.2": "Sleep, a closed lid, shutdown or quitting Blave: auto-trading stops, positions stay on {venue} and are not closed.",
    "tr.means.2p": "Sleep, a closed lid, shutdown or quitting Blave: auto-trading stops; paper positions stay open and are not closed.",
    "tr.means.3": "If a bar close was missed while away, trading is auto-paused, not even reductions are made, until you confirm each strategy.",
    "tr.means.4": "Stop orders placed on the exchange are not affected by this computer; consider placing them.",
    "tr.tab.over": "Overview",
    "tr.tab.pos": "Positions",
    "tr.tab.assets": "Assets",
    "tr.tab.hist": "Order History",
    "tr.tab.set": "Settings",
    "tr.onboard": "Order sizes are derived from your exchange equity, so this page needs an exchange account first. Once connected, give each strategy an amount and it starts trading.",
    "tr.strategies": "Strategies",
    "tr.zeroMeansOff": "0 means no orders — the strategy still runs and computes its signal; it just holds no position.",
    "tr.col.strategy": "Strategy",
    "tr.col.symbol": "Symbol",
    "tr.col.amount": "Position size",
    "tr.col.targetPos": "Target position",
    "tr.col.target": "Target",
    "tr.col.actual": "Actual",
    "tr.col.diff": "Difference",
    "tr.mkt.spot": "Spot",
    "tr.mkt.swap": "Perp",
    "tr.amountAria": "Amount ({ccy})",
    "tr.noStrategies": "No strategy is ready to trade yet. Ask the agent for one — once it has a backtest you can give it a size.",
    "tr.typeC": "portfolio strategies do not support auto-trading yet",
    "tr.gateHint": "Below the {m} {c} minimum entry — no position will open",
    "tr.total": "Total",
    "tr.ofEquity": "of your equity",
    "tr.unitNote": "Amounts in {c}",
    "tr.unsaved": "Amounts not saved yet — they take effect on Save.",
    "tr.revert": "Revert",
    "tr.save": "Save",
    "tr.saving": "Saving…",
    "tr.saved": "Saved — this computer now uses the new amounts.",
    "tr.saveTitle": "Confirm trade amounts",
    "tr.saveWarn": "Once saved, the order engine reconciles to these amounts — orders may fire immediately.",
    "tr.saveRemoved": "Removing: {names} — their futures positions will be closed and spot holdings sold.",
    "tr.saveLine": "{name}: {amt}",
    "tr.exchPositions": "Exchange positions",
    "tr.threshold": "Reconciliation skips a difference under {amt}, or one that converts to less than the exchange's minimum order size for that symbol; once both are cleared, it submits the order automatically.",
    "tr.posEmpty": "No open positions.",
    "tr.noPositions": "No positions yet — every strategy's order amount is 0. Set an amount above and check back.",
    "tr.noReconcile": "No reconcile yet — actual positions appear once auto-trading runs.",
    "tr.gateFootLead": "Skipped this round: ",
    "tr.gateFootEntry": "{sym} difference under {m}",
    "tr.gateFootReduce": "{sym} over by under half a lot",
    "tr.orderFailed": "Order failed: {sym} — {err}",
    "tr.account": "Account",
    "tr.equity": "Equity",
    "tr.recentOrders": "Recent orders",
    "tr.noOrders": "No orders yet.",
    "tr.contributors": "Triggered by {names}",
    "tr.orderTarget": "Order target {amount}",
    "tr.unbind": "Disconnect",
    "tr.unbinding": "Disconnecting…",
    "tr.unbindDesc": "Removes the exchange keys from this computer — the order engine can no longer trade this account.",
    "tr.unbindWarn": "This removes the exchange keys from this computer — the order engine can no longer trade this account. Your order settings are also cleared; you'll need to set them up again after reconnecting.",
    "tr.ov.equity": "Total equity",
    "tr.ov.equityTip": "All accounts combined, incl. unrealized PnL.",
    "tr.ov.day": "Today's PnL",
    "tr.ov.curve": "Equity curve",
    "tr.ov.modeEquity": "Equity",
    "tr.ov.modePnl": "Cumulative PnL",
    "tr.ov.rangeAll": "All",
    "tr.ov.empty": "No equity records yet. While Blave is open, this computer records one on the hour; nothing is recorded while it is closed.",
    "tr.ov.emptyBaseline": "Not enough records to draw the curve yet — it takes two. While Blave is open, one is recorded on the hour; nothing is recorded while it is closed.",
    "tr.ov.gapNote": "Gaps in the curve are times Blave wasn't open — nothing was recorded.",
    "tr.ov.range": "Range",
    "tr.ov.curveAria": "Equity curve, {a} to {b}, {n} records",
    "tr.ov.evResume": "Trading resumed",
    "tr.ov.evResumeNote": "new entries resumed",
    "tr.ov.evConnected": "Connected {venue}",
    "tr.ov.evDisconnected": "Disconnected {venue}",
    "tr.ov.events": "Events",
    "tr.ov.evEmpty": "No events in this range.",
    "tr.ov.today": "Today",
    "tr.ov.yesterday": "Yesterday",
    "tr.ov.evHalt": "Trading paused",
    "tr.ov.evHaltAuto": "Trading auto-paused",
    "tr.ov.evHaltNote": "new entries paused; exits and stops still run",
    "tr.ov.evDowntimeNote": "Everything is frozen — no reducing or closing either. To resume, press “Start trading” and choose whether to sync positions.",
    "tr.ov.evErr": "Order failed",
    "tr.ov.evBarStale": "Bar has not arrived",
    "tr.ov.evBarStaleNote": "waited {minutes} min and still retrying; the signal will be late",
    "tr.ov.evExUnreach": "{venue} unreachable for {minutes} min",
    "tr.ov.evExUnreachNote": "no orders go out meanwhile and trading resumes by itself once it is back; a temporary exchange fault usually needs nothing from you, but if it drags on, check the exchange's announcements",
    "tr.ov.evExBack": "{venue} reachable again",
    "tr.ov.evExecFallback": "Fell back to a market order",
    "tr.ov.evExecFallbackNote": "the execution style set for this order could not run, so the fill price may differ from what you expected",
    "tr.ov.evExecInterrupted": "Previous execution interrupted",
    "tr.ov.evExecInterruptedNote": "fills may be missing from the ledger; check positions before resuming",
    "tr.ov.evExecStuck": "Execution stuck",
    "tr.ov.evExecStuckNote": "further orders for this symbol are waiting on it",
    "tr.ov.evSchedErr": "Scheduler errored",
    "tr.ov.evSchedErrNote": "this strategy may not run at all until it is fixed",
    "tr.ov.evStrategyFailed": "Strategy crashed",
    "tr.ov.evStrategyFailedNote": "the schedule keeps firing, but this run produced no signal",
    "tm.pause": "Pause trading (keep positions)",
    "tm.open": "Open Blave",
    "tm.quit": "Quit Blave…",
    "tm.notifTitle": "Trading paused",
    "tm.notifBody": "No new positions will be opened; existing positions are untouched. To resume, press Start trading on the Auto trading page in Blave.",
    "tm.pauseFail": "The pause command didn’t go through, so it may still be trading. Open Blave and press Pause trading again.",
    "tm.quitTitle": "Auto trading is still running",
    "tm.quitBody": "After Blave quits, this computer places no more orders and closes nothing; positions stay at {venue}. When you open Blave again, press Start trading to resume.",
    "tm.quitGo": "Quit Blave",
    "tm.quitStay": "Cancel",
    "tm.hidden": "Blave is still open and auto trading keeps running. Use the menu bar icon to pause or to open the window.",
    "tm.updateReady": "A new version is ready: pause trading to update, or it installs when you quit Blave",
    "tm.evOrderErrNote": "The exchange rejected an order. Open Blave to see why.",
    "env.aria": "Environment",
    "env.local": "This computer",
    "env.cloud": "Cloud",
    "env.st.signedOut": "Signed out",
    "env.st.none": "Not started",
    "env.st.autoPaused": "Auto-paused",
    "env.tip": "{where} — {money}, {state}",
    "env.tip1": "{where} — {x}",
    "env.cellAria1": "{where}: {x}",
    "env.winTitle": "Blave — {where} · {money}",
    "env.winTitle0": "Blave — {where}",
    "tr.mode.real": "Real",
    "side.cloud.starting": "Machine starting",
    "side.cloud.emptyCut1": "No strategies in the cloud yet.",
    "side.cloud.st.trading": "Trading",
    "side.cloud.st.halted": "Halted",
    "env.empty.title": "Cloud",
    "env.empty.desc": "No cloud machine yet",
    "env.open.h": "Put your strategies in the cloud and they keep running with this computer off",
    "env.open.1": "A machine that stays on, running your strategies on schedule around the clock and placing orders.",
    "env.open.2": "Shutting down this computer, closing the lid or losing the network changes nothing.",
    "env.open.3": "Blave’s market and positioning data is included at no extra charge.",
    "env.open.more": "See the Full Plan",
    "side.cloud.emptyGate": "Once the cloud machine is up, your strategies are listed here.",
    "env.empty.starting": "The cloud machine is starting, usually about a minute. This page changes to the cloud’s content once it is up.",
    "env.empty.relogin": "Sign in to Blave again to see your cloud machine. Chats and strategies on this computer aren’t affected.",
    "env.empty.unreach": "The cloud’s state can’t be read right now. Trading already running in the cloud isn’t affected.",
    "tr.ro.note": "In this version the app can only view the cloud. To set amounts, start or pause trading, use the cloud workspace on the web for now.",
    "tr.ro.noteEmpty": "In this version the app can only view the cloud. To connect an exchange, use the cloud workspace on the web for now.",
    "tr.cloud.unknown": "Can’t read the cloud’s state",
    "tr.cloud.stale": "Last updated {t}",
    "tr.cloud.unreach": "Couldn’t read the cloud’s trading state. What’s shown is from {t}. Trading already running in the cloud isn’t affected.",
    "tr.cloud.stoppedBody": "The balance fell under {m} TWD and the machine stopped. Trading has halted. Positions remain at the exchange and nothing is managing them. A stopped machine still bills {h} TWD an hour. At a balance of 0 the machine is deleted, along with the strategies, data and keys on it.",
    "tr.cloud.stoppedBody0": "The balance ran low and the machine stopped. Trading has halted. Positions remain at the exchange and nothing is managing them. A stopped machine is still billed. At a balance of 0 the machine is deleted, along with the strategies, data and keys on it.",
    "tr.cloud.unbindDesc": "Removes the exchange keys from the cloud machine — the order engine can no longer trade this account.",
    "chat.tgt.label": "Target",
    "chat.tgt.cut1": "In this version the agent can’t work on the cloud machine yet.",
    "tm.stLocal": "This computer: {money} · {state}",
    "tm.stCloud": "Cloud: {money} · {state}",
    "tm.stOn": "Running",
    "tm.stPaused": "Paused",
    "tm.stUnknown": "Status unavailable",
    "tm.pauseLocal": "Pause trading on this computer (leave positions)",
    "tm.quitCloudNote": "Trading in the cloud isn’t affected and keeps running.",
    "tm.notifPrefixLocal": "This computer: ",
    "tm.notifPrefixCloud": "Cloud: ",
    "menu.site": "Blave Website",
    "menu.view": "View",
    "minv.chat": "This version of Blave needs an update before it can keep using Blave’s AI. This message was not sent and used no AI.",
    "minv.trade": "This version of Blave needs an update before it can start trading. Pausing isn’t affected. Update at the bottom of Settings › General.",
    "minv.btn": "Go to Update",
    "set.cat.priv": "Privacy",
    "priv.switch": "Send usage data",
    "priv.lead": "It tells us where people get stuck. Turning it off stops sending immediately.",
    "priv.leadOff": "Off. This computer no longer sends anything. Nothing else in the app is affected.",
    "priv.collect.h": "Collected",
    "priv.collect.hOff": "Collected when on",
    "priv.collect.1": "Which step you reached: first open, daily open, connected an AI (which kind), signed in, first backtest, trading started (paper or real), ran in the cloud",
    "priv.collect.2": "When it happened",
    "priv.collect.3": "The app version, macOS version and system language",
    "priv.collect.4": "An installation ID (a random ID for this install); after you sign in it is linked to your Blave account",
    "priv.never.h": "Never collected",
    "priv.never.1": "Chat content",
    "priv.never.2": "Strategy code and names",
    "priv.never.3": "Symbols, amounts, positions",
    "priv.never.4": "Any keys",
    "priv.never.5": "File paths",
    "priv.never.6": "Event records contain no IP address",
    "priv.fine": "Records are kept for 25 months. Anything that can’t be sent is dropped, and nothing in the app depends on it.",
    "priv.kept": "Records sent before you turned this off are still kept for 25 months.",
    "priv.id": "Installation ID",
    "priv.idCopy": "Copy",
    "priv.idCopied": "Copied",
    "priv.idNote": "Include this ID when you email us to delete the usage data sent from this computer.",
    "cx.apiKey": "API Key",
    "cx.secretKey": "Secret Key",
    "cx.group.crypto": "Crypto",
    "cx.ip.copied": "Copied",
    "cx.ip.loading": "Looking up…",
    "cx.ip.fail": "You may not be signed in to Blave, or this network is IPv6-only. The whitelist needs this computer’s public IPv4.",
    "cx.ip.noneLong": "Couldn’t find this computer’s public IP",
    "cx.ip.retry": "Look Up Again",
    "cx.chk.withdraw": "This key has withdrawals enabled, so it was not saved. Turn withdrawals off at Binance, then connect again.",
    "cx.chk.trading": "This key has no trading permission, so it was not saved. Usually the IP whitelist is missing: add the IP above to the whitelist, enable trading, then connect again.",
    "cx.chk.tradingNoIp": "This key has no trading permission, so it was not saved. Usually the IP whitelist is missing: set the whitelist, enable trading, then connect again.",
    "cx.chk.ipOrKey": "Binance rejected this key, so it was not saved. Binance doesn’t tell these three causes apart: the IP above isn’t on the whitelist, the API Key was pasted wrong, or the key was deleted. Check the whitelisted IP first.",
    "cx.chk.keyFormat": "The API Key’s format is wrong, so it was not saved. Copy it from Binance again, with no spaces before or after.",
    "cx.chk.secret": "The Secret Key doesn’t match this API Key, so it was not saved. Copy the secret from Binance again. It is shown only once, when the key is created; if you no longer have it, create a new key.",
    "cx.chk.clock": "This computer’s clock is too far off Binance’s, so the key couldn’t be checked and was not saved. Turn on automatic date and time in System Settings, then connect again.",
    "cx.chk.rate": "Binance is temporarily limiting requests from this IP, so the key couldn’t be checked and was not saved. Wait a few minutes before trying again. Repeated retries extend the limit.",
    "cx.chk.network": "Couldn’t reach Binance, so the key couldn’t be checked and was not saved. Check the network, then connect again.",
    "cx.chk.unknown": "Binance returned a result that couldn’t be read, so the permissions couldn’t be confirmed and the key was not saved. Try again in a few minutes.",
    "cx.chk.noWhitelist": "This key has no IP whitelist. Binance deletes keys that have no whitelist and sit unused for 30 days; adding this computer’s public IP to the whitelist is recommended.",
    "cx.chk.sendFail": "The key passed the check but was not saved on this computer ({err}). Connect again.",
    "cx.re.tradingOff": "Trading permission was turned off, so orders can’t be placed. Turn it back on at Binance, then press Retest connection.",
    "cx.re.ipChanged": "The public IP changed. Update the whitelist at Binance to the IP below, then press Retest connection.",
    "cx.re.rejected": "Binance rejected this key, so orders can’t be placed. Check the whitelisted IP. If the key is gone, reconnect.",
    "tm.key.ipTitle": "{where}: public IP changed",
    "tm.key.ipBody": "Update the Binance whitelist to {ip}, then press Retest connection in Auto trading › Settings. Orders can’t be placed until then.",
    "tm.key.rejTitle": "{where}: Binance rejected the key",
    "tm.key.rejSameIpBody": "Check at Binance that the key still exists and its permissions are unchanged. If it’s gone, create a new one, then unbind and reconnect in Auto trading › Settings. Orders can’t be placed until then.",
    "tm.key.rejUnknownBody": "Open Auto trading › Settings to check the IP and the key: the public IP may have changed, or the key may have been deleted. Orders can’t be placed until then.",
    "tm.key.permTitle": "{where}: trading was turned off for the Binance key",
    "tm.key.permBody": "Turn trading permission back on for this key at Binance, then press Retest connection in Auto trading › Settings. Orders can’t be placed until then.",
    "tr.hostLock": "The previous order engine is still shutting down; retrying automatically ({n}/{max}). No orders go out meanwhile.",
    "cx.re.badKey": "The key saved on this computer no longer matches Binance (the secret or the API Key is wrong), so orders can’t be placed. Press Unbind, then connect again.",
    "cx.note.noFutures": "This key has no futures trading permission: spot strategies can trade, but Binance will reject orders from futures strategies. To run futures strategies, enable it at Binance, then press Retest connection. If it can’t be enabled (keys created before you opened a futures account can’t), create a new key and connect again.",
    "cx.note.noSpot": "This key has no spot trading permission: futures strategies can trade, but Binance will reject orders from spot strategies. To run spot strategies, enable it at Binance, then press Retest connection. If it can’t be enabled, create a new key and connect again.",
    "cx.ip.copyThis": "Copy this IP",
  },
  zh: {
    "cn.h": "Blave 不內建 AI。",
    "cn.blave.title": "用 Blave 的 AI",
    "cn.blave.desc": "首次綁卡送 100 TWD 的 AI 額度，之後按用量計費",
    "cn.blave.btn": "登入 Blave",
    "cn.blave.switch": "切換",
    "cn.local.label": "這台電腦上的 agent",
    "cn.local.desc": "Blave 不收 AI 費用",
    "cn.redetect": "重新偵測",
    "cn.detecting": "偵測中…",
    "cn.connect": "連結",
    "cn.foot": "連結後可以隨時更換。",
    "st.signedIn": "已登入",
    "st.notSignedIn": "尚未登入",
    "st.notFound": "未偵測到",
    "oauth.waiting": "等待瀏覽器授權…",
    "oauth.cancel": "取消等待",
    "oauth.opened": "已在瀏覽器開啟授權頁，完成後會自動回到這裡。",
    "oauth.failed": "授權失敗。",
    "OAUTH_CANCELLED": "已取消。要用 Blave 的 AI 再按一次。",
    "OAUTH_TIMEOUT": "授權逾時（5 分鐘）。",
    "OAUTH_STATE_MISMATCH": "回來的授權跟這次請求對不上，已擋下。",
    "OAUTH_NO_CODE": "瀏覽器回來了，但沒有帶授權碼。",
    "OAUTH_DENIED": "你在瀏覽器取消了授權。",
    "KEYCHAIN_UNAVAILABLE": "這台電腦無法安全儲存憑證（Keychain 不可用），沒有保存。",
    "TOKEN_EXCHANGE_FAILED": "授權碼換不到 token。",
    "ws.chatExample": "回測一支 BTC 20/50 均線策略",
    "ws.strategies": "策略",
    "ws.noStrategies": "還沒有策略。",
    "ws.placeholder": "跟 agent 說一句話",
    "ws.send": "送出",
    "ws.settings": "設定",
    "turn.process": "思考過程",
    "turn.thinking": "思考中",
    "turn.running": "執行中 · 第 {n} 步",
    "turn.busy": "上一輪還在跑。",
    "turn.engineFailed": "引擎準備失敗：{msg}",
    "turn.exit": "引擎退出碼 {code}",
    "turn.error": "出錯了：{msg}",
    "fault.authInvalid": "這台電腦的 Blave 登入已失效，這一輪沒有跑。",
    "fault.authBtn": "重新登入 Blave",
    "fault.noCredit": "Blave 餘額用完了，這一輪沒有跑。",
    "fault.noCreditBtn": "儲值",
    "conn.expired": "Blave 登入已失效，重新登入後繼續。",
    "engine.workspace": "建立工作區 ~/Blave/workspace …",
    "engine.deps": "正在安裝策略需要的 Python 套件（pandas、numpy…），只有第一次…",
    "engine.preparing": "正在準備引擎（第一次會安裝，約一分鐘）…",
    "mp.model": "模型",
    "mp.effort": "思考深度",
    "mp.default": "預設",
    "mp.aria": "模型與思考深度：{model}，{effort}",
    "mp.ariaNoEffort": "模型：{model}",
    "mp.cap": "{model} 的預設是「{level}」。越高想得越久、用得越多。",
    "mp.none": "這個模型沒有思考深度可調。",
    "lv.low": "低",
    "lv.medium": "中",
    "lv.high": "高",
    "lv.xhigh": "超高",
    "lv.max": "最高",
    "lv.ultra": "Ultra",
    "fault.noModel": "你的帳號用不了「{model}」，這一輪沒有跑。",
    "fault.noModelSwitched": "你的帳號用不了「{model}」，這一輪沒有跑。已換回「{to}」。",
    "fault.noModelBtn": "選別的模型",
    "mp.na": "你的方案沒有",
    "rp.tab.backtest": "回測數據",
    "rp.tab.trades": "進出場紀錄",
    "rp.tab.code": "程式碼",
    "bt.fee": "手續費",
    "bt.totalReturn": "總報酬",
    "bt.benchmark": "基準報酬",
    "bt.benchmarkRank": "贏過 {n}% 隨機投組",
    "bt.sharpe": "Sharpe",
    "bt.maxDrawdown": "最大回撤",
    "bt.trades": "交易次數",
    "bt.mcpt": "MCPT p 值",
    "bt.mcptTipSig": "隨機打亂 {n} 次，只有 {pct} 的結果比它好；低於 0.05 是慣用門檻。",
    "bt.mcptTipNs": "隨機打亂 {n} 次，有 {pct} 的結果比它好——沒過 0.05 的慣用門檻，這組結果分不出是實力還是運氣。",
    "bt.equity": "權益",
    "bt.drawdown": "回撤",
    "bt.chartAria": "回測期間的權益曲線與回撤",
    "bt.monthly": "月報酬",
    "bt.year": "全年",
    "bt.empty": "這支策略沒有回測資料。",
    "tr.empty": "這支策略沒有進出場紀錄。",
    "tr.chartError": "圖表畫不出來，下方的進出場紀錄仍可查看。",
    "tr.list": "進出場紀錄",
    "tr.count": "{n} 筆",
    "tr.buy": "買進",
    "tr.sell": "賣出",
    "tr.kind.open": "開倉",
    "tr.kind.close": "平倉",
    "tr.kind.flip": "翻向",
    "tr.position": "部位 {n}",
    "bt.grpReturns": "報酬",
    "bt.grpRisk": "風險",
    "bt.grpTrading": "交易",
    "bt.annReturn": "年化報酬",
    "bt.annVol": "年化波動率",
    "bt.sortino": "Sortino",
    "bt.omega": "Omega",
    "bt.winRate": "日勝率",
    "bt.totalFees": "總手續費",
    "bt.mcptDistTitle": "MCPT · 隨機打亂 {n} 次的 Sharpe 分佈，p = {p}",
    "bt.mcptDistActual": "實際 Sharpe {v}",
    "bt.mcptDistUnit": "次",
    "ws.resizeSide": "調整策略欄寬度",
    "ws.resizeChat": "調整聊天欄寬度",
    "ws.sideCollapse": "收合策略欄",
    "ws.sideExpand": "展開策略欄",
    "ws.chatCollapse": "收合聊天欄",
    "ws.chatExpand": "展開聊天欄",
    "set.close": "關閉",
    "set.cats": "設定分類",
    "set.cat.display": "一般",
    "set.cat.model": "模型接入",
    "set.lang": "語言",
    "up.app": "Blave {v}",
    "up.latest": "已是最新版",
    "up.checking": "正在檢查更新…",
    "up.downloading": "正在下載 {nv}…",
    "up.downloadingPct": "正在下載 {nv}（{pct}%）",
    "up.ready": "{nv} 已下載，重新啟動後生效",
    "up.blocked": "{nv} 已下載。自動下單執行中不會更新；暫停下單後可以更新，或結束 Blave 時自動安裝",
    "up.error": "這次沒檢查成功",
    "up.staging": "{nv} 下載完成，正在準備安裝…",
    "up.installFailed": "{nv} 下載好了，但沒有裝成功。請確認 Blave 放在「應用程式」資料夾裡（不是從下載的磁碟映像直接開），再檢查一次",
    "up.install": "重新啟動並更新",
    "up.check": "檢查更新",
    "cn.current": "使用中",
    "cs.all": "所有對話",
    "cs.back": "返回對話",
    "cs.new": "新對話",
    "cs.del": "刪除對話",
    "cs.delConfirm": "刪除？",
    "strat.del": "移到垃圾桶",
    "bt.tip.totalReturn": "整段回測期間的累計報酬，已扣手續費。",
    "bt.tip.annReturn": "把總報酬換算成一年的複利報酬，方便跟不同長度的回測比較。",
    "bt.tip.benchmark": "同一段期間買進後一直持有這個標的的報酬。策略要贏過它，才算比什麼都不做好。",
    "bt.tip.benchmarkRank": "跟隨機挑標的、買進持有的投組比，這支策略的總報酬贏過其中多少。",
    "bt.tip.annVol": "每日報酬的標準差換算成一年。數字越大，權益的起伏越劇烈。",
    "bt.tip.maxDrawdown": "權益從高點跌到之後最低點的最大跌幅，也就是最壞的時候帳面會少掉多少。",
    "bt.tip.sharpe": "每承擔一單位波動換到多少報酬（年化，無風險利率以 0 計）。越高越好。",
    "bt.tip.sortino": "算法同 Sharpe，但只把下跌的波動當成風險，上漲的波動不扣分。",
    "bt.tip.omega": "所有賺錢時段的報酬總和，除以所有虧錢時段的虧損總和。大於 1 表示賺的比賠的多。",
    "bt.tip.trades": "部位有變動的次數：進場、出場、加減碼各算一次。",
    "bt.tip.winRate": "有損益的日子裡，賺錢的日子佔多少。這不是每筆交易的勝率。",
    "bt.tip.totalFees": "整段期間付出的手續費加總，以佔資金的百分比表示。",
    "del.title": "刪除「{title}」？",
    "del.titleCur": "刪除目前這個對話？",
    "del.body": "這條對話的聊天記錄會刪除，無法復原。策略不受影響。",
    "del.bodyCur": "聊天記錄會刪除，無法復原。刪除後會開一條新對話。策略不受影響。",
    "del.cancel": "取消",
    "del.ok": "刪除",
    "chat.imageAlt": "agent 傳來的圖",
    "cn.signIn": "登入",
    "login.opened": "已在瀏覽器開啟 {name} 登入頁，完成後回到這裡。",
    "login.ok": "{name} 已登入。",
    "login.failed": "{name} 登入沒有完成。",
    "fault.localAuth": "{name} 目前沒有登入，這一輪沒有跑。",
    "fault.localAuthBtn": "登入 {name}",
    "chat.imageZoom": "放大檢視",
    "login.cancel": "取消等待",
    "login.failedCmd": "也可以在終端機執行 {cmd}。",
    "login.retry": "再試一次",
    "fault.resend": "再送一次",
    "fault.resendDone": "已重新送出",
    "fault.authOk": "Blave 已重新登入。",
    "cn.blave.signOut": "登出",
    "cn.blave.signOutLocalOnly": "這台電腦已登出，但連不上伺服器、沒能撤銷這台裝置的授權。到 blave.org 的設定 › 裝置再撤銷一次。",
    "acct.noCard": "Blave 的 AI 還不能用：這個帳號還沒綁卡。",
    "acct.noCredit": "Blave 的 AI 還不能用：餘額是 0。",
    "acct.addCard": "前往綁卡",
    "acct.sub": "首次綁卡有 {q} TWD 的 AI 額度，{t} 天內電腦版也拿得到 Blave 的資料。",
    "acct.ready": "可以開始了。",
    "acct.creditIn": "額度到了，可以再送了。",
    "fault.needCard": "用 Blave 的 AI 要先綁卡，這一輪沒有跑。",
    "fault.checking": "這一輪沒有跑，正在確認帳號狀態。",
    "set.cat.plan": "資料與雲端方案",
    "plan.st.running": "已啟動 · 主機運行中",
    "plan.st.stopped": "已停機 · 餘額低於 {m} TWD",
    "plan.st.stoppedNoAmt": "已停機 · 餘額不足",
    "plan.bill": "計費",
    "plan.month": "{p} TWD／月",
    "plan.hour": "以 30 天計 ＝ 每個整點從餘額扣 {h} TWD",
    "plan.trialFree": "{d}前免主機費，之後照上面的價格。",
    "plan.topup": "餘額低於 {a} TWD 時，會從綁定的卡自動儲值 {b} TWD；可以在網頁關閉。",
    "plan.start": "啟動方案",
    "plan.starting": "啟動中…",
    "plan.addCredit": "前往儲值",
    "plan.addCard": "前往綁卡",
    "plan.openWs": "前往工作頁",
    "plan.manage": "前往網頁停用",
    "plan.manageStopped": "前往網頁管理",
    "cf.title": "啟動 Blave Agent 雲端方案？",
    "cf.body1": "會替這個帳號開一台雲端主機，通常 1 分鐘左右。Blave 的資料一啟動就能用。",
    "cf.body2": "開好後每個整點從餘額扣 {h} TWD（每月 {p} TWD，以 30 天計）；主機存在就會扣，不管有沒有在用。",
    "cf.body2Trial": "{d}前免主機費；之後每個整點從餘額扣 {h} TWD，主機存在就會扣，不管有沒有在用。",
    "cf.body3": "要停止收費，需到網頁刪除主機。",
    "cf.ok": "啟動",
    "plan.err.credit": "餘額不足，沒有啟動。",
    "plan.err.nocard": "這個帳號還沒綁卡，沒有啟動。",
    "plan.err.relogin": "啟動方案前要重新登入一次。聊天與策略不受影響。",
    "plan.relogin": "重新登入",
    "plan.err.server": "啟動沒有完成。再按一次不會重複開主機。",
    "plan.err.rate": "按得太頻繁了，請過一陣子再試。不會重複開主機。",
    "plan.err.slow": "比平常久。主機還在啟動，不需要再按一次。",
    "plan.recheck": "重新查看",
    "data.starting": "雲端主機啟動中；Blave 的資料馬上就能用。",
    "plan.done": "雲端主機開好了。",
    "side.trial": "試用剩 {n} 天",
    "side.starting": "啟動中",
    "side.stopped": "已停機",
    "data.ready": "Blave 的資料可以用了。",
    "pv.h.offer": "首次綁卡，送 {t} 天 Blave 的資料",
    "pv.h.offerNoNum": "首次綁卡，送一段試用期的 Blave 資料",
    "pv.h.plan": "策略上線的雲端主機，含 Blave 的資料",
    "pv.h.ready": "Blave 的資料可以用了",
    "pv.h.starting": "雲端主機啟動中，通常 1 分鐘左右",
    "pv.h.running": "策略可以在雲端主機上線了",
    "pv.h.stopped": "主機停機了，但還在扣款",
    "pv.h.unknown": "查不到這個帳號的狀態",
    "pv.d.offer.cli": "AI 照用你的 {name}。想讓策略全天候自動執行，這 {t} 天開雲端主機也免主機費。",
    "pv.d.offer.blave": "另有 {q} TWD 的 AI 額度。想讓策略全天候自動執行，這 {t} 天開雲端主機也免主機費。",
    "pv.d.noTrial": "Blave Agent 雲端方案：{p} TWD／月。這個帳號沒有首次綁卡的試用，綁卡後要回來啟動方案才有資料。",
    "pv.d.trial": "到 {d}為止，不用啟動方案。之後，資料在 Blave Agent 雲端方案裡：{p} TWD／月。",
    "pv.d.plan": "Blave Agent 雲端方案：{p} TWD／月。策略在這台主機上照排程執行、自動下單；電腦版不啟動也能用，只是沒有 Blave 的資料。",
    "pv.d.included": "想讓策略全天候自動執行，才需要啟動 Blave Agent 雲端方案：{p} TWD／月。",
    "pv.d.starting": "Blave 的資料現在就能用，不用等主機開好。可以關掉這個視窗。",
    "pv.d.running": "到工作頁在這台主機上新增策略、設定定期報告、連接交易所。電腦上做的策略留在電腦上，兩邊各是一份。",
    "pv.d.stopped": "停機期間仍每小時扣 {h} TWD。餘額歸零時主機會刪除，主機上的策略與資料一併清除。",
    "pv.d.noPrice": "AI 照用你現在的設定。試用結束後要資料，再啟動 Blave Agent 雲端方案。",
    "pv.d.unknown": "可能是網路問題。重新查看不會花錢。",
    "pv.f.out": "{t} 天後要資料，再啟動雲端方案（{p} TWD／月）。",
    "pv.f.offer": "綁卡時收 {v} TWD 驗證金，全額進你的餘額，並開啟自動儲值。{t} 天後要資料，再啟動雲端方案（{p} TWD／月）。",
    "pv.f.noTrial": "綁卡時最少儲值 {b} TWD，全額進你的餘額，並開啟自動儲值。",
    "pv.f.trial": "想讓策略全天候自動執行，現在就能啟動：{d}前免主機費，之後主機存在就扣，刪除才停。",
    "pv.f.plan": "每個整點從餘額扣 {h} TWD。主機存在就扣，停機照扣，刪除才停。",
    "pv.f.running": "每個整點從餘額扣 {h} TWD（{p} TWD／月）。停用＝到網頁刪除主機，主機上的策略與資料一併清除。",
    "pv.w.out.cli": "登入不花錢，也不改你用的 AI。下一步是綁卡。",
    "pv.w.noTrial": "下一步：回來啟動方案。",
    "pv.w.waiting": "瀏覽器已開啟，請在那邊按「允許」。",
    "pv.st.trial": "試用中 · 剩 {n} 天",
    "pv.st.none": "未啟動",
    "pv.st.ok": "可用",
    "pv.st.starting": "啟動中",
    "pv.more": "方案內容與計費",
    "plan.inc": "內含",
    "plan.rule": "主機存在就會扣，不管有沒有在用；停機照扣，刪除主機才停。",
    "plan.rule.running": "主機存在就會扣，不管有沒有在用。停用＝刪除主機，主機上的策略與資料會一併清除。",
    "pv.more.once": "首次綁卡的試用每人一次、每張卡一次。",
    "pv.inc.1": "一台 24 小時開著的雲端主機：策略照排程執行、自動下單",
    "pv.inc.2": "Blave 的資料，電腦版與雲端主機都拿得到",
    "pv.inc.3": "從瀏覽器的工作頁操作這台主機",
    "pv.inc.note": "電腦上做的策略留在電腦上。主機上的策略在工作頁建立，交易所金鑰也在那邊綁。",
    "pv.signin": "登入 Blave",
    "pv.e.out": "這台還拿不到 Blave 的資料。登入 Blave 後首次綁卡，送 {t} 天；AI 照用你的 {name}。",
    "pv.e.outNoNum": "這台還拿不到 Blave 的資料。登入 Blave 後首次綁卡，送一段試用期；AI 照用你的 {name}。",
    "pv.e.card": "這台還拿不到 Blave 的資料。首次綁卡，送 {t} 天。",
    "pv.e.card.cli": "這台還拿不到 Blave 的資料。首次綁卡，送 {t} 天；AI 照用你的 {name}。",
    "pv.e.noTrial": "這台還拿不到 Blave 的資料：它在 Blave Agent 雲端方案裡。",
    "pv.e.sub": "之後資料在每月 {p} TWD 的 Blave Agent 雲端方案裡。",
    "pv.e.subN": "每月 {p} TWD：一台讓策略全天候自動執行的雲端主機，含 Blave 的資料；主機存在就按小時扣。",
    "pv.e.unknown": "這台還拿不到 Blave 的資料。現在查不到帳號狀態，到「資料與雲端方案」重新查看。",
    "pv.e.btn": "資料與雲端方案",
    "cn.blave.signinSwitch": "登入並切換",
    "set.cat.acct": "帳號",
    "cn.blave.name": "Blave 的 AI",
    "cn.blave.group": "由 Blave 提供",
    "acct.out.1": "登出之後，這台電腦不再取得 Blave 的資料。",
    "acct.out.2": "對話與策略都留在這台電腦，不受影響。",
    "acct.out.3": "你現在用的是 Blave 的 AI，登出會回到選 AI 的畫面，要先選一個才能繼續用。",
    "acct.in.1": "登入之後才拿得到 Blave 的資料與雲端方案。",
    "acct.in.2": "登入不花錢，也不改你用的 AI。",
    "acct.toPlan": "餘額、綁卡與雲端方案在「資料與雲端方案」。",
    "acct.toPlanBtn": "前往",
    "acct.lbl": "Blave 帳號",
    "acct.signedOut": "未登入",
    "acct.signedIn": "已登入",
    "acct.out": "登出",
    "acct.outDone": "已登出。這台不再拿得到 Blave 的資料。",
    "cx.lead": "只存在這台電腦的工作區（~/Blave/workspace/.env），Blave 不會上傳。agent 和你的策略程式讀得到，才能替你下單、抓資料。",
    "cx.note.one": "在 Binance 建金鑰時：只開交易權限、提領務必關閉，並把這個 IP 加進白名單。",
    "cx.store.q": "金鑰存在哪？",
    "cx.acct.meta": "可以下單、讀帳戶，也會用來抓這家交易所的資料。一次只能連一個。",
    "cx.venue": "交易所／券商",
    "cx.paper": "模擬交易（免金鑰）",
    "cx.paperShort": "模擬交易",
    "cx.paperNote": "不用任何 API 金鑰。模擬帳戶起始 10,000 USDT，用你策略的行情資料即時成交、計手續費（不含滑價），不動真錢；策略、下單設定、部位與績效頁全部照真實帳戶的方式運作。要改用真實交易所時，先解除綁定再連接即可。",
    "cx.connect": "連接交易所",
    "cx.connecting": "串接中…",
    "cx.connected": "已連接",
    "cx.perfNote": "模擬交易的績效不代表真實成交的結果（不含滑價）。",
    "cx.retest": "重新測試",
    "cx.retesting": "測試中…",
    "cx.fail": "{id} 串接失敗（{stage}）：{msg}",
    "cx.failShort": "串接失敗",
    "cx.sendFail": "連接沒有完成（{err}）。再按一次試試。",
    "cx.down": "這台電腦的下單機沒有在跑。過幾秒再試；一直這樣就重開 Blave。",
    "tr.mode.paper": "模擬",
    "tr.tb": "{state} · {venue}",
    "tr.tbAria": "自動下單：{state}",
    "tr.paperCcy": "模擬 {c}",
    "tr.nav": "自動下單",
    "tr.autoOn": "自動下單執行中",
    "tr.halted": "已暫停",
    "tr.recDead": "對帳沒有在跑",
    "tr.lastBeat": "最後心跳 {t}",
    "tr.notStarted": "尚未啟動下單",
    "tr.noAccount": "還沒連接交易所",
    "tr.loading": "載入中…",
    "tr.stop": "暫停下單",
    "tr.start": "啟動下單",
    "tr.stopping": "暫停中…",
    "tr.starting": "啟動中…",
    "tr.cmdNotDelivered": "指令沒有送到，它還在交易。再按一次試試；一直失敗的話，到交易所撤銷這台電腦的 API key——它就再也送不出單（既有部位仍需你自己在交易所平倉）。",
    "tr.cmdUnavailable": "這台電腦的指令通道沒有回應，現在送不出指令。",
    "tr.cmdFailed": "指令沒有送到，什麼都沒有改變。再按一次試試。",
    "tr.cmdUnknown": "指令送出去了，但這台電腦還沒回報結果，可能已經執行。先看這一頁的狀態，再決定要不要重按。",
    "tr.cmdRejected": "這台電腦沒有接受這個指令（{err}）。",
    "tr.hostRetry": "這台電腦的下單機停了，正在重新啟動，這段時間不會下單。起來之後看這裡的狀態；如果顯示尚未啟動，再按一次「啟動下單」。",
    "tr.hostShort": "下單機沒有在跑",
    "tr.hostDown": "這台電腦的下單機起不來，自動下單沒有在跑。請重開 Blave。",
    "tr.unknown": "讀不到這台電腦的下單狀態",
    "tr.unknownBody": "這一輪讀不到下單狀態，所以帳戶與部位暫時顯示不出來，過幾秒會再試。",
    "tr.unknownStop": "下單機可能還在跑；要停的話，按上面的「暫停下單」。",
    "tr.badAmount": "看不懂這個金額。只收數字，例如 1500 或 1,500.50；上限 1,000,000,000。",
    "tr.stopChoiceSelf": "暫停後不會再開任何新倉。「關閉部位」只會平掉自動下單建立的部位，你手動開的單不會被動到。",
    "tr.stopChoice": "暫停後不會再開任何新倉。「關閉部位」會市價平掉這個帳戶上的所有部位，包含你自己手動開的單。",
    "tr.closeAllWarn2": "策略金額會保留：之後按「啟動下單」，下單機會照現有金額把部位重建回來；不想重建，先把金額歸零。",
    "tr.stopKeep": "暫停，不動部位",
    "tr.stopFlat": "暫停並關閉部位",
    "tr.startChoice": "「補齊部位」會立刻用市價把部位補到策略目前的訊號狀態——策略若已在場內，等於中途上車；「等新訊號」現在不下單，每條策略等它下次進場、出場或翻向才開始交易。",
    "tr.startWarn1": "會重新開始送出真實委託，照目前的權重把交易所部位調到目標。",
    "tr.startWarn2": "策略跟權重在暫停期間照常更新，所以第一次對帳可能一次調整多個部位。",
    "tr.startCatchUp": "啟動並補齊部位",
    "tr.startWait": "啟動，等新訊號才進場",
    "tr.means.l": "在這台電腦上跑，代表：",
    "tr.means.1": "自動下單只在電腦醒著、Blave 開著、連得上網的時候跑。",
    "tr.means.2": "睡眠、闔蓋、關機、結束 Blave：自動下單停止，部位留在{venue}，不會自動平倉。",
    "tr.means.2p": "睡眠、闔蓋、關機、結束 Blave：自動下單停止，模擬部位留著，不會自動平倉。",
    "tr.means.3": "恢復後如果錯過了 K 棒收盤，會自動暫停下單，連減倉都不會做，等你逐支確認。",
    "tr.means.4": "交易所端的停損單不受這台電腦影響；建議替部位掛上。",
    "tr.tab.over": "總覽",
    "tr.tab.pos": "部位",
    "tr.tab.assets": "資產",
    "tr.tab.hist": "交易歷史",
    "tr.tab.set": "設定",
    "tr.onboard": "下單金額是從交易所的淨值算出來的，所以這頁要先接一個交易所帳戶。接好之後，每檔策略填一個金額就會開始下單。",
    "tr.strategies": "策略",
    "tr.zeroMeansOff": "填 0 就是不下單——策略照常跑、照常算訊號，只是不會有部位。",
    "tr.col.strategy": "策略",
    "tr.col.symbol": "標的",
    "tr.col.amount": "部位大小",
    "tr.col.targetPos": "目標部位",
    "tr.col.target": "目標",
    "tr.col.actual": "實際",
    "tr.col.diff": "差額",
    "tr.mkt.spot": "現貨",
    "tr.mkt.swap": "合約",
    "tr.amountAria": "金額（{ccy}）",
    "tr.noStrategies": "還沒有可以下單的策略。先請代理做一檔，回測跑完就能設金額。",
    "tr.typeC": "投資組合策略暫不支援自動下單",
    "tr.gateHint": "低於最小進場 {m} {c}，不會進場",
    "tr.total": "合計",
    "tr.ofEquity": "你淨值的",
    "tr.unitNote": "金額單位：{c}",
    "tr.unsaved": "金額尚未儲存，按「儲存」才會生效。",
    "tr.revert": "還原",
    "tr.save": "儲存",
    "tr.saving": "儲存中…",
    "tr.saved": "已儲存，這台電腦已套用新金額。",
    "tr.saveTitle": "確認下單金額",
    "tr.saveWarn": "儲存後，下單機會照新的金額對帳，可能立即產生下單。",
    "tr.saveRemoved": "移出組合：{names}——其合約部位將自動平倉、現貨庫存將自動賣出。",
    "tr.saveLine": "{name}：{amt}",
    "tr.exchPositions": "交易所部位",
    "tr.threshold": "差額小於 {amt}，或換算後不到該標的在交易所的最小下單量，對帳都不下單；兩個都達到就自動送出委託。",
    "tr.posEmpty": "目前無未平倉部位。",
    "tr.noPositions": "還沒有部位，策略金額都是 0，先在上面填一個金額再回來看。",
    "tr.noReconcile": "還沒有對帳紀錄，實際部位要等自動下單跑起來才看得到。",
    "tr.gateFootLead": "這輪不下單：",
    "tr.gateFootEntry": "{sym} 差額不到 {m}",
    "tr.gateFootReduce": "{sym} 超出不到半口",
    "tr.orderFailed": "下單失敗：{sym}——{err}",
    "tr.account": "帳戶",
    "tr.equity": "淨值",
    "tr.recentOrders": "最近下單",
    "tr.noOrders": "還沒有下過單。",
    "tr.contributors": "由 {names} 觸發",
    "tr.orderTarget": "下單目標 {amount}",
    "tr.unbind": "解除綁定",
    "tr.unbinding": "解除中…",
    "tr.unbindDesc": "移除這台電腦上的交易所金鑰，下單機不再能用這個帳戶交易。",
    "tr.unbindWarn": "會把這個交易所的金鑰從這台電腦移除，下單機將無法再用這個帳戶交易。下單設定也會一併清空，重新串接後需重新設定。",
    "tr.ov.equity": "總權益",
    "tr.ov.equityTip": "全帳戶合計，含未實現損益。",
    "tr.ov.day": "當日損益",
    "tr.ov.curve": "權益曲線",
    "tr.ov.modeEquity": "權益",
    "tr.ov.modePnl": "累積損益",
    "tr.ov.rangeAll": "全部",
    "tr.ov.empty": "還沒有權益紀錄。Blave 開著的時候，這台電腦每個整點記一筆；關著的時段不會有紀錄。",
    "tr.ov.emptyBaseline": "紀錄還不夠畫出曲線，要兩筆。Blave 開著的時候每個整點記一筆；關著的時段不會有紀錄。",
    "tr.ov.gapNote": "曲線斷開的地方＝Blave 沒開著，沒有紀錄。",
    "tr.ov.range": "區間",
    "tr.ov.curveAria": "權益曲線，{a} 到 {b}，{n} 筆",
    "tr.ov.evResume": "已恢復下單",
    "tr.ov.evResumeNote": "恢復開新倉",
    "tr.ov.evConnected": "已連接 {venue}",
    "tr.ov.evDisconnected": "已解除 {venue}",
    "tr.ov.events": "事件",
    "tr.ov.evEmpty": "這段期間沒有事件。",
    "tr.ov.today": "今天",
    "tr.ov.yesterday": "昨天",
    "tr.ov.evHalt": "已暫停下單",
    "tr.ov.evHaltAuto": "已自動暫停下單",
    "tr.ov.evHaltNote": "停開新倉；平倉與停損停利照常執行",
    "tr.ov.evDowntimeNote": "全部凍結，減倉與平倉也不會自動做；要恢復請按「啟動下單」，由你決定要不要補齊部位",
    "tr.ov.evErr": "下單失敗",
    "tr.ov.evBarStale": "K 棒沒到位",
    "tr.ov.evBarStaleNote": "等了 {minutes} 分鐘，仍在重試，訊號會晚發",
    "tr.ov.evExUnreach": "{venue} 已連續 {minutes} 分鐘連不上",
    "tr.ov.evExUnreachNote": "這段時間不會下單，恢復後自動繼續；交易所暫時故障通常不需要處理，持續很久的話請確認交易所公告",
    "tr.ov.evExBack": "{venue} 已恢復連線",
    "tr.ov.evExecFallback": "已改用市價單",
    "tr.ov.evExecFallbackNote": "原本設定的下單方式無法執行，成交價可能與預期不同",
    "tr.ov.evExecInterrupted": "前次執行中斷",
    "tr.ov.evExecInterruptedNote": "成交可能沒記進帳本，重新啟動前先核對部位",
    "tr.ov.evExecStuck": "執行卡住",
    "tr.ov.evExecStuckNote": "這個標的的後續下單都在等它",
    "tr.ov.evSchedErr": "排程器出錯",
    "tr.ov.evSchedErrNote": "修好之前這支策略可能完全不會跑",
    "tr.ov.evStrategyFailed": "策略執行失敗",
    "tr.ov.evStrategyFailedNote": "排程還是照跑，但這一輪沒有產生訊號",
    "tm.pause": "暫停下單（不動部位）",
    "tm.open": "打開 Blave",
    "tm.quit": "結束 Blave…",
    "tm.notifTitle": "已暫停下單",
    "tm.notifBody": "停開新倉；部位沒有動。要恢復，到 Blave 的「自動下單」按「啟動下單」。",
    "tm.pauseFail": "暫停的指令沒有送到，它可能還在交易。打開 Blave 再按一次「暫停下單」。",
    "tm.quitTitle": "自動下單還在執行",
    "tm.quitBody": "結束 Blave 之後，這台電腦就不會再下單，也不會平倉；部位留在{venue}。再開 Blave 時要重新按「啟動下單」。",
    "tm.quitGo": "結束 Blave",
    "tm.quitStay": "取消",
    "tm.hidden": "Blave 還開著，自動下單照常執行。從選單列的圖示可以暫停或打開視窗。",
    "tm.updateReady": "新版已就緒：暫停下單後可以更新，或結束 Blave 時自動安裝",
    "tm.evOrderErrNote": "交易所拒絕了這筆單；打開 Blave 看原因",
    "env.aria": "環境",
    "env.local": "這台電腦",
    "env.cloud": "雲端",
    "env.st.signedOut": "未登入",
    "env.st.none": "未啟動",
    "env.st.autoPaused": "已自動暫停",
    "env.tip": "{where} — {money}，{state}",
    "env.tip1": "{where} — {x}",
    "env.cellAria1": "{where}：{x}",
    "env.winTitle": "Blave — {where} · {money}",
    "env.winTitle0": "Blave — {where}",
    "tr.mode.real": "真錢",
    "side.cloud.starting": "主機啟動中",
    "side.cloud.emptyCut1": "雲端還沒有策略。",
    "side.cloud.st.trading": "下單中",
    "side.cloud.st.halted": "已停",
    "env.empty.title": "雲端",
    "env.empty.desc": "還沒有雲端主機",
    "env.open.h": "把策略放上雲端，電腦關機也照跑",
    "env.open.1": "一台一直開著的主機，策略全天候照排程執行、自動下單。",
    "env.open.2": "這台電腦關機、闔蓋、沒網路，都不影響。",
    "env.open.3": "Blave 的行情與籌碼資料含在裡面，不另外收。",
    "env.open.more": "看完整方案內容",
    "side.cloud.emptyGate": "雲端主機開好之後，策略會列在這裡。",
    "env.empty.starting": "雲端主機啟動中，通常 1 分鐘左右。開好後這一頁會自己換成雲端的內容。",
    "env.empty.relogin": "重新登入一次 Blave 之後才看得到你的雲端主機。這台電腦上的對話與策略不受影響。",
    "env.empty.unreach": "現在讀不到雲端的狀態。雲端上正在跑的下單不受影響。",
    "tr.ro.note": "這一版在 app 裡只能看。要設金額、啟動或暫停下單，先到網頁的雲端工作頁。",
    "tr.ro.noteEmpty": "這一版在 app 裡只能看。要連接交易所，先到網頁的雲端工作頁。",
    "tr.cloud.unknown": "讀不到雲端狀態",
    "tr.cloud.stale": "最後更新 {t}",
    "tr.cloud.unreach": "讀不到雲端的下單狀態。這裡顯示的是 {t} 的內容；雲端上正在跑的下單不受影響。",
    "tr.cloud.stoppedBody": "餘額低於 {m} TWD，主機已停機。下單已停止，部位留在交易所、現在沒有人在管。停機期間仍每小時扣 {h} TWD；餘額歸零時主機會刪除，主機上的策略、資料與金鑰一併清除。",
    "tr.cloud.stoppedBody0": "餘額不足，主機已停機。下單已停止，部位留在交易所、現在沒有人在管。停機期間仍會扣主機費；餘額歸零時主機會刪除，主機上的策略、資料與金鑰一併清除。",
    "tr.cloud.unbindDesc": "移除雲端主機上的交易所金鑰，下單機不再能用這個帳戶交易。",
    "chat.tgt.label": "操作對象",
    "chat.tgt.cut1": "這一版 agent 還不能操作雲端主機。",
    "tm.stLocal": "這台電腦：{money} · {state}",
    "tm.stCloud": "雲端：{money} · {state}",
    "tm.stOn": "執行中",
    "tm.stPaused": "已暫停",
    "tm.stUnknown": "讀不到狀態",
    "tm.pauseLocal": "暫停這台電腦的下單（不動部位）",
    "tm.quitCloudNote": "雲端的下單不受影響，照常執行。",
    "tm.notifPrefixLocal": "這台電腦：",
    "tm.notifPrefixCloud": "雲端：",
    "menu.site": "Blave 官網",
    "menu.view": "顯示",
    "minv.chat": "這個版本的 Blave 需要更新，才能繼續用 Blave 的 AI。這則訊息沒有送出，沒有用到 AI。",
    "minv.trade": "這個版本的 Blave 需要更新，才能啟動下單。暫停不受影響。到 設定 › 一般 最下面更新。",
    "minv.btn": "去更新",
    "set.cat.priv": "隱私",
    "priv.switch": "傳送使用資料",
    "priv.lead": "用來知道大家卡在哪一步。關掉就立刻停止傳送。",
    "priv.leadOff": "已關閉，這台電腦不再傳送。其他功能不受影響。",
    "priv.collect.h": "會收",
    "priv.collect.hOff": "開啟時會收",
    "priv.collect.1": "做到哪一步：首次開啟、每日開啟、完成連結（哪一種 AI）、登入、第一次回測、啟動下單（模擬或真錢）、上雲端運行",
    "priv.collect.2": "發生的時間",
    "priv.collect.3": "app 版本、macOS 版本、系統語言",
    "priv.collect.4": "安裝識別碼（這份安裝隨機產生的編號）；登入後會跟你的帳號對上",
    "priv.never.h": "不收",
    "priv.never.1": "對話內容",
    "priv.never.2": "策略的程式碼與名稱",
    "priv.never.3": "標的、金額、部位",
    "priv.never.4": "任何金鑰",
    "priv.never.5": "檔案路徑",
    "priv.never.6": "事件紀錄不含 IP 位址",
    "priv.fine": "紀錄保留 25 個月。送不出去就丟掉，不影響任何功能。",
    "priv.kept": "關掉之前送出的紀錄仍保留 25 個月。",
    "priv.id": "安裝識別碼",
    "priv.idCopy": "複製",
    "priv.idCopied": "已複製",
    "priv.idNote": "要我們刪除這台電腦送出的使用資料時，請在來信裡附上這組識別碼。",
    "cx.apiKey": "API Key",
    "cx.secretKey": "Secret Key",
    "cx.group.crypto": "加密貨幣",
    "cx.ip.copied": "已複製",
    "cx.ip.loading": "查詢中…",
    "cx.ip.fail": "可能是還沒登入 Blave，或這個網路只有 IPv6。白名單要填這台電腦的對外 IPv4。",
    "cx.ip.noneLong": "查不到這台電腦的對外 IP",
    "cx.ip.retry": "再查一次",
    "cx.chk.withdraw": "這把金鑰的提領權限是開著的，沒有儲存。到 Binance 把提領關掉，再回來連一次。",
    "cx.chk.trading": "這把金鑰沒開交易權限，沒有儲存。通常是還沒設 IP 白名單：把上面的 IP 加進白名單、勾選交易權限，再連一次。",
    "cx.chk.tradingNoIp": "這把金鑰沒開交易權限，沒有儲存。通常是還沒設 IP 白名單：設好白名單、勾選交易權限，再連一次。",
    "cx.chk.ipOrKey": "Binance 拒絕了這把金鑰，沒有儲存。Binance 不區分這三種原因：白名單裡沒有上面這個 IP、API Key 貼錯、金鑰已被刪除。先核對白名單裡的 IP。",
    "cx.chk.keyFormat": "API Key 的格式不對，沒有儲存。從 Binance 重新複製一次，前後不要帶空白。",
    "cx.chk.secret": "Secret Key 對不上這把 API Key，沒有儲存。從 Binance 重新複製 Secret；它只在建立金鑰時顯示一次，找不到就要重建一把。",
    "cx.chk.clock": "這台電腦的時間跟 Binance 差太多，沒辦法檢查，沒有儲存。到系統設定打開「自動設定時間」，再連一次。",
    "cx.chk.rate": "Binance 暫時限制了這個 IP 的請求，沒辦法檢查，沒有儲存。請等幾分鐘再試；連續重試會讓限制變長。",
    "cx.chk.network": "連不上 Binance，沒辦法檢查，沒有儲存。確認網路後再連一次。",
    "cx.chk.unknown": "Binance 回了看不懂的結果，沒辦法確認權限，沒有儲存。過幾分鐘再試。",
    "cx.chk.noWhitelist": "這把金鑰沒有設 IP 白名單。Binance 會刪除沒有白名單、又閒置 30 天的金鑰；建議把這台電腦的對外 IP 加進白名單。",
    "cx.chk.sendFail": "金鑰通過了檢查，但沒有存進這台電腦（{err}）。再連一次。",
    "cx.re.tradingOff": "交易權限被關掉了，下單送不出去。到 Binance 重新開啟，再按「重新測試」。",
    "cx.re.ipChanged": "對外 IP 換了。到 Binance 把白名單改成下面這個 IP，再按「重新測試」。",
    "cx.re.rejected": "Binance 拒絕了這把金鑰，下單送不出去。核對白名單的 IP；金鑰不在了就重新連接。",
    "tm.key.ipTitle": "{where}：對外 IP 換了",
    "tm.key.ipBody": "到 Binance 把白名單改成 {ip}，再到「自動下單 › 設定」按「重新測試」。改好之前下單送不出去。",
    "tm.key.rejTitle": "{where}：Binance 拒絕了金鑰",
    "tm.key.rejSameIpBody": "到 Binance 確認這把金鑰還在、權限沒被改；不在就重建一把，到「自動下單 › 設定」解除綁定後重新連接。改好之前下單送不出去。",
    "tm.key.rejUnknownBody": "打開「自動下單 › 設定」核對 IP 與金鑰：可能是對外 IP 換了，或金鑰被刪除。改好之前下單送不出去。",
    "tm.key.permTitle": "{where}：Binance 金鑰的交易權限被關掉了",
    "tm.key.permBody": "到 Binance 重新打開這把金鑰的交易權限，再到「自動下單 › 設定」按「重新測試」。改好之前下單送不出去。",
    "tr.hostLock": "上一次的下單機還沒完全停下來，正在自動重試（{n}/{max}）。這段時間不會下單。",
    "cx.re.badKey": "這台電腦上存的金鑰對不上 Binance 了（Secret 或 API Key 的內容不對），下單送不出去。按「解除綁定」，再重新連接一次。",
    "cx.note.noFutures": "這把金鑰沒有開合約交易權限：現貨策略可以下單，合約策略的下單會被 Binance 拒絕。要跑合約策略，到 Binance 開啟後按「重新測試」；開不了的話（金鑰建在開通合約帳戶之前就會這樣），重建一把金鑰再連接。",
    "cx.note.noSpot": "這把金鑰沒有開現貨交易權限：合約策略可以下單，現貨策略的下單會被 Binance 拒絕。要跑現貨策略，到 Binance 開啟後按「重新測試」；開不了的話，重建一把金鑰再連接。",
    "cx.ip.copyThis": "複製這個 IP",
  },
};
