const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("blave", {
  detectAgents: () => ipcRenderer.invoke("detect-agents"),
  saveConnection: (choice) => ipcRenderer.invoke("save-connection", choice),
  loadConnection: () => ipcRenderer.invoke("load-connection"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  getLocale: () => ipcRenderer.invoke("get-locale"),
  deleteStrategy: (name) => ipcRenderer.invoke("delete-strategy", name),
  listSessions: () => ipcRenderer.invoke("list-sessions"),
  loadSessionImages: (id) => ipcRenderer.invoke("load-session-images", id),
  loadSession: (id) => ipcRenderer.invoke("load-session", id),
  deleteSession: (id) => ipcRenderer.invoke("delete-session", id),
  listStrategies: () => ipcRenderer.invoke("list-strategies"),
  loadStrategy: (name) => ipcRenderer.invoke("load-strategy", name),
  accountStatus: () => ipcRenderer.invoke("account-status"),
  planStart: () => ipcRenderer.invoke("plan-start"),
  publicPricing: () => ipcRenderer.invoke("public-pricing"),
  tradeLabels: (labels) => ipcRenderer.send("trade-labels", labels),
  updateState: () => ipcRenderer.invoke("update-state"),
  updateCheck: () => ipcRenderer.invoke("update-check"),
  updateInstall: () => ipcRenderer.invoke("update-install"),
  onUpdateState: (fn) => ipcRenderer.on("update-state", (_e, st) => fn(st)),
  telemetryNoticed: () => ipcRenderer.invoke("telemetry-noticed"),
  telemetryGet: () => ipcRenderer.invoke("telemetry-get"),
  telemetrySet: (on) => ipcRenderer.invoke("telemetry-set", on),
  tradeStatus: () => ipcRenderer.invoke("trade-status"),
  tradeEvents: (q) => ipcRenderer.invoke("trade-events", q),
  tradeEquity: (q) => ipcRenderer.invoke("trade-equity", q),
  tradeSend: (cmd, args) => ipcRenderer.invoke("trade-send", cmd, args),
  modelOptions: (kind) => ipcRenderer.invoke("model-options", kind),
  loadModelPrefs: () => ipcRenderer.invoke("load-model-prefs"),
  saveModelPrefs: (prefs) => ipcRenderer.invoke("save-model-prefs", prefs),
  startOAuth: (lang) => ipcRenderer.invoke("start-oauth", lang),
  cancelOAuth: () => ipcRenderer.invoke("cancel-oauth"),
  clearConnection: () => ipcRenderer.invoke("clear-connection"),
  hasBlaveToken: () => ipcRenderer.invoke("has-blave-token"),
  cancelAgentLogin: () => ipcRenderer.invoke("cancel-agent-login"),
  agentLogin: (kind) => ipcRenderer.invoke("agent-login", kind),
  signOutBlave: () => ipcRenderer.invoke("sign-out-blave"),
  ensureEngine: () => ipcRenderer.invoke("ensure-engine"),
  sendMessage: (payload) => ipcRenderer.invoke("send-message", payload),
  onEngineProgress: (fn) => ipcRenderer.on("engine-progress", (_e, t) => fn(t)),
  onTurnEvent: (fn) => ipcRenderer.on("turn-event", (_e, c) => fn(c)),
  onTurnEnd: (fn) => ipcRenderer.on("turn-end", (_e, r) => fn(r)),
});
