const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("blave", {
  detectAgents: () => ipcRenderer.invoke("detect-agents"),
  saveConnection: (choice) => ipcRenderer.invoke("save-connection", choice),
  loadConnection: () => ipcRenderer.invoke("load-connection"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  getLocale: () => ipcRenderer.invoke("get-locale"),
  deleteStrategy: (name) => ipcRenderer.invoke("delete-strategy", name),
  listSessions: () => ipcRenderer.invoke("list-sessions"),
  loadSessionImages: (id) => ipcRenderer.invoke("load-session-images", id),
  loadSession: (id) => ipcRenderer.invoke("load-session", id),
  deleteSession: (id) => ipcRenderer.invoke("delete-session", id),
  listStrategies: () => ipcRenderer.invoke("list-strategies"),
  loadStrategy: (name) => ipcRenderer.invoke("load-strategy", name),
  accountStatus: () => ipcRenderer.invoke("account-status"),
  planStart: () => ipcRenderer.invoke("plan-start"),
  publicPricing: () => ipcRenderer.invoke("public-pricing"),
  tradeLabels: (labels) => ipcRenderer.send("trade-labels", labels),
  cloudStatus: () => ipcRenderer.invoke("cloud-status"),
  cloudRefresh: () => ipcRenderer.invoke("cloud-refresh"),
  onCloudState: (fn) => ipcRenderer.on("cloud-state", (_e, s) => fn(s)),
  // 最低版本閘:{ blocked, min, current, checked_at };被擋時 trade-send 的啟動類回 UPDATE_REQUIRED、send-message 回 { blocked: "UPDATE_REQUIRED" }
  minVersionState: () => ipcRenderer.invoke("min-version-state"),
  onMinVersionState: (fn) => ipcRenderer.on("min-version-state", (_e, st) => fn(st)),
  // app 選單「顯示」的兩項:"local" | "cloud"
  onEnvSwitch: (fn) => ipcRenderer.on("env-switch", (_e, env) => fn(env)),
  updateState: () => ipcRenderer.invoke("update-state"),
  updateCheck: () => ipcRenderer.invoke("update-check"),
  updateInstall: () => ipcRenderer.invoke("update-install"),
  onUpdateState: (fn) => ipcRenderer.on("update-state", (_e, st) => fn(st)),
  telemetryGet: () => ipcRenderer.invoke("telemetry-get"),
  telemetrySet: (on) => ipcRenderer.invoke("telemetry-set", on),
  telemetryInstallId: () => ipcRenderer.invoke("telemetry-install-id"),
  featureFlags: () => ipcRenderer.invoke("feature-flags"),
  // 自帶資料來源:金鑰的值只經過 dataSrcSave 一次;其餘三支只有名稱
  dataSrcList: () => ipcRenderer.invoke("datasrc-list"),
  dataSrcSave: (input) => ipcRenderer.invoke("datasrc-save", input),
  dataSrcBlockers: (name) => ipcRenderer.invoke("datasrc-blockers", name),
  dataSrcRemove: (name) => ipcRenderer.invoke("datasrc-remove", name),
  // Binance 真錢連接:金鑰只經過 binanceConnect 一次(主行程查過權限才存);其餘三支不碰金鑰
  binanceIp: () => ipcRenderer.invoke("binance-ip"),
  binanceState: () => ipcRenderer.invoke("binance-state"),
  binanceRecheck: () => ipcRenderer.invoke("binance-recheck"),
  binanceConnect: (apiKey, secret) => ipcRenderer.invoke("binance-connect", { apiKey, secret }),
  onBinanceState: (fn) => ipcRenderer.on("binance-state", (_e, st) => fn(st)),
  tradeStatus: () => ipcRenderer.invoke("trade-status"),
  tradeEvents: (q) => ipcRenderer.invoke("trade-events", q),
  tradeEquity: (q) => ipcRenderer.invoke("trade-equity", q),
  tradeSend: (cmd, args) => ipcRenderer.invoke("trade-send", cmd, args),
  modelOptions: (kind) => ipcRenderer.invoke("model-options", kind),
  loadModelPrefs: () => ipcRenderer.invoke("load-model-prefs"),
  saveModelPrefs: (prefs) => ipcRenderer.invoke("save-model-prefs", prefs),
  startOAuth: (lang) => ipcRenderer.invoke("start-oauth", lang),
  cancelOAuth: () => ipcRenderer.invoke("cancel-oauth"),
  clearConnection: () => ipcRenderer.invoke("clear-connection"),
  hasBlaveToken: () => ipcRenderer.invoke("has-blave-token"),
  cancelAgentLogin: () => ipcRenderer.invoke("cancel-agent-login"),
  agentLogin: (kind) => ipcRenderer.invoke("agent-login", kind),
  signOutBlave: () => ipcRenderer.invoke("sign-out-blave"),
  ensureEngine: () => ipcRenderer.invoke("ensure-engine"),
  sendMessage: (payload) => ipcRenderer.invoke("send-message", payload),
  onEngineProgress: (fn) => ipcRenderer.on("engine-progress", (_e, t) => fn(t)),
  onTurnEvent: (fn) => ipcRenderer.on("turn-event", (_e, c) => fn(c)),
  onTurnEnd: (fn) => ipcRenderer.on("turn-end", (_e, r) => fn(r)),
});
